[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Friday CS Project"
authors = [{name = "The Friday CS Project Group", email = "don't doxx us please"}]
dynamic = ["version", "description"]
